### ISSUE TITLE
Comment fonctionne la présence dans deux zones ?

### ISSUE THREAD

**Issue by Oldarorn** [izio38/iZone#1]
Bonjour,

Je poste mon issue ici parce que je me suis retrouvé face à un cas hier et ça m'a poussé à m'interroger. Si je découpe une zone 2 dans une zone 1, je suis considéré dans la zone 2 et dans la zone 1 ou juste la 2 ? J'aurai voulu savoir si un mode de filtrage était possible ou si je devais découper de façon plus précise mes deux zones pour éviter que l'une rentre dans l'eau ?

Merci pour cette ressource qui dépanne énormément :)

**Comment by IzioDev** [comment]
salut!

Je pense que les deux zones reverront true.
aussi il serait possible d'implémenter le fait de récupérer la liste des zones dans lequel le joueur se trouve .
Ça pourrait résoudre ta question.
je m'y pencherai bientôt

**Comment by IzioDev** [comment]
Le dernier commit permet d'utiliser:
```lua
Citizen.CreateThread(function()
    while true do
        Wait(100)
        TriggerEvent("izone:getAllZonesThePlayerIsIn", function(zones)
            print(json.encode(zones))
        end)
    end
end)
```
