### ISSUE TITLE
Deux zones avec le même nom répondent true et false

### ISSUE THREAD

**Issue by Oldarorn** [izio38/iZone#2]
En gros :
Si deux zones portent le même nom, la première zone créée répondra true et la seconde répondra false, ainsi que la troisième etc...

Vu qu'Izone utilise des catégories, un trigger via le nom des cat ne serait pas tout aussi intéressant ?

**Comment by IzioDev** [comment]
oui on pourrait envisager l'ajout d'un événement `isPlayerInCatZone` je m'y pencherai :)

**Comment by Oldarorn** [comment]
Merci de ta réponse, j'voudrais pas abuser en demandant tout ça mais ça me semblait pertinent sur le coup :D

**Comment by IzioDev** [comment]
Le dernier commit permet d'utiliser:

```lua
Citizen.CreateThread(function()
    while true do
        Wait(100)
        TriggerEvent("izone:isPlayerInCatZone", "foot", "field1", function(isIn)
            print(isIn)
        end)
    end
end)
```
