### ISSUE TITLE
Nui GUI is not working properly

### ISSUE THREAD

**Issue by mcshi14** [izio38/iZone#3]
After installing the sql and starting in my server, when i press the button create new zone the mouse does not unfocus correctly and you get stuck without being able to create any zone

**Comment by IzioDev** [comment]
are you using the last version?
could you reporduce the step?

**Comment by mcshi14** [comment]
yea, im using the last version
to reproduce the issue just import sql into database and then start it into
the server and on the nui press create new zone or the x symbol. The nui
focus doesnt deactivate, i mean the screen has a mouse with no html on it
when pressing

**Comment by izio38** [comment]
Actually fuck you dude

**Comment by izio38** [comment]
I dont care about your shit tbh

**Comment by mcshi14** [comment]
lol reported

**Comment by FrenchBoomer** [comment]
Bonjour Izio j'ai le même soucis quand je clique sur créer une nouvelle zone le html se ferme nickel mais par contre ma souris se désactive pas comme si j'était toujours sur la page html et du coup je suis totalement bloquer je ne peut pas utiliser ton merveilleux script :/

**Comment by IzioDev** [comment]
je regarde ça

Le lun. 9 sept. 2019 à 06:24, Walter White <notifications@github.com> a
écrit :

**Comment by IzioDev** [comment]
@mcshi14 I'm really sorry to the answers upper, my account was hijacked :(.
I just retreive it

**Comment by IzioDev** [comment]
```lua
RegisterNUICallback('save', function(data, cb)
    SetNuiFocus(false, false)
    isInUse = false
    TriggerServerEvent("izone:saveZone", points, data.name, data.cat)
    points = {}
end)
```

Quand tu sauvegardes c'est ce block qui est executé je ne vois pas pourquoi le focus reste. 
C'est quand tu sauvegardes après avoir entré un nom dans l'input? On est d'accord?

**Comment by IzioDev** [comment]
J'ai une autre idée.
Comment s'appel ton dossier où se trouve izone?
Essayes de renommer le dossier resource en `izone` (dans le server.cfg aussi)

**Comment by FrenchBoomer** [comment]
Ben écoute Izio super tu as régler mon soucis donc je te remercie grandement pour ton aide et ta rapidité de réponse c'est super cool de ta part :) 
Félicitation pour se superbe script et que tu as release a la communauté c'est super sympa de ta part mec merci beaucoup

**Comment by IzioDev** [comment]
Content de l'entendre :)

Le lun. 9 sept. 2019 à 08:23, Walter White <notifications@github.com> a
écrit :
