### ISSUE TITLE
Option to view zones

### ISSUE THREAD

**Issue by hadesownage** [izio38/iZone#5]
Hi, it will be nice to have an option in UI to see the zones after you made them.

**Comment by IzioDev** [comment]
You mean to see the area ? Like display the line draw ?

**Comment by Spudgun** [comment]
I think @hadesownage is asking for an option in the admin menu to show the zone like you do when creating. See below.

![image](https://i.imgur.com/YSXXn6O.png)
![image](https://i.imgur.com/xpVPbOo.png)

I agree this would be super helpful for viewing already created zones.

**Comment by IzioDev** [comment]
I just added the feature. Please, make sure to read the warning in the readme (changelog section), there is a small breaking change (you have to rename a db property).
