### ISSUE TITLE
Manage Zones - Zones overflow outside of screen

### ISSUE THREAD

**Issue by Spudgun** [izio38/iZone#6]
Hi,

Just found this issue when you get over a certain amount of zones.

![image](https://user-images.githubusercontent.com/3261320/85189710-5033c580-b305-11ea-87ec-45fcda2a344f.png)

Also, would it be possible to move the Saving Zone window to the middle of the screen?

![image](https://user-images.githubusercontent.com/3261320/85189734-88d39f00-b305-11ea-8591-da3c2995f257.png)

Kind Regards,
Spudgun

**Comment by IzioDev** [comment]
Ui improvments have been made. Please, make sure to read the warning in the readme (changelog section), there is a small breaking change (you have to rename a db property).
